feat: Use GitHub Composite Actions (#30)
* Use GitHub Composite Actions
* Add error handling
* Update API Version to 2022-11-28 
  * https://docs.github.com/en/rest/overview/api-versions?apiVersion=2022-11-28

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,11 +19,33 @@ inputs:
 outputs:
   job_id:
     description: "job_id of target workflow jobs"
+    value: ${{ steps.request.outputs.job_id }}
   html_url:
     description: "html_url of target workflow jobs"
-runs:
-  using: "docker"
-  image: "Dockerfile"
+    value: ${{ steps.request.outputs.html_url }}
+
 branding:
   icon: "link"
   color: "blue"
+
+runs:
+  using: 'composite'
+  steps:
+    - name: Parse job_id
+      id: request
+      env:
+        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
+        INPUT_REPOSITORY: ${{ inputs.repository }}
+        INPUT_RUN_ID: ${{ inputs.run_id }}
+        INPUT_JOB_NAME: ${{ inputs.job_name }}
+        INPUT_PER_PAGE: ${{ inputs.per_page }}
+      shell: bash
+      run: |
+        GITHUB_BASEURL=https://api.github.com
+        GITHUB_API="/repos/${INPUT_REPOSITORY:-${GITHUB_REPOSITORY}}/actions/runs/${INPUT_RUN_ID:-${GITHUB_RUN_ID}}/jobs"
+        JOBINFO="$(curl --get -Ss -H "Authorization: Bearer ${INPUT_GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "${GITHUB_BASEURL}${GITHUB_API}?per_page=${INPUT_PER_PAGE:-30}")"
+        echo "${JOBINFO}" | grep "Resource not accessible by integration" &&  exit 1
+        eval "$(echo ${JOBINFO} | jq -r --arg job_name "${INPUT_JOB_NAME}" '.jobs | map(select(.name == $job_name)) | .[0] | @sh "job_id=\(.id) html_url=\(.html_url)"')"
+        echo ${job_id} | grep "null" > /dev/null && echo "parse error, job_id is ${job_id}. job name might be wrong. See https://github.com/Tiryoh/gha-jobid-action" && exit 1
+        echo "job_id=${job_id}" >> $GITHUB_OUTPUT
+        echo "html_url=${html_url}" >> $GITHUB_OUTPUT
